<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

return new class extends Migration
{
    public function up(): void
    {
        $now = Carbon::now();
        $stages = ['proposal', '60', '100'];

        foreach ($stages as $stage) {
            $templateId = DB::table('defense_rubric_templates')->insertGetId([
                'name' => match ($stage) {
                    'proposal' => 'Proposal Defense Rubric',
                    '60' => '60% Defense Rubric',
                    default => '100% Defense Rubric',
                },
                'stage' => $stage,
                'is_active' => true,
                'description' => 'Default rubric template generated by system migration.',
                'grade_guidelines' => json_encode([
                    ['min' => 96, 'max' => 100, 'label' => 'Excellent'],
                    ['min' => 90, 'max' => 95, 'label' => 'Very Good'],
                    ['min' => 85, 'max' => 89, 'label' => 'Good'],
                    ['min' => 80, 'max' => 84, 'label' => 'Fair'],
                    ['min' => 75, 'max' => 79, 'label' => 'Passed'],
                    ['min' => 0, 'max' => 74, 'label' => 'Failed'],
                ]),
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            $criteria = [
                ['group', 'Software', 50, 1],
                ['group', 'Document - Completeness', 15, 2],
                ['group', 'Document - Acceptability', 20, 3],
                ['group', 'Oral Presentation - Presentation', 10, 4],
                ['group', 'Oral Presentation - Visual Tools', 5, 5],
                ['individual', 'Individual Contribution', 100, 6],
            ];

            foreach ($criteria as [$scope, $name, $maxPoints, $sort]) {
                DB::table('defense_rubric_criteria')->insert([
                    'defense_rubric_template_id' => $templateId,
                    'scope' => $scope,
                    'name' => $name,
                    'max_points' => $maxPoints,
                    'sort_order' => $sort,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }
    }

    public function down(): void
    {
        DB::table('defense_rubric_templates')->whereIn('name', [
            'Proposal Defense Rubric',
            '60% Defense Rubric',
            '100% Defense Rubric',
        ])->delete();
    }
};

